config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  resources :customers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    before_action :set_customer, only: %i[ edit update show destroy ]

    def index
        @customers = Customer.all
    end

    def new
        @customer = Customer.new
    end

    def create
        @customer = Customer.new(customers_params)

        if @customer.save
            redirect_to customers_path, notice: "Cliente cadastrado com sucesso"
        else
            render :new
        end
    end

    def show
        @customer = Customer.find(params[:id])
    end

    def edit
        @customer = Customer.find(params[:id])
    end

    def update
        @customer = Customer.find(params[:id])

        if @customer.update(customers_params)
            redirect_to customer_path(@customer.id), notice: "Cliente atualizado com sucesso"
        else
            render :edit
        end
    end

    def destroy
        if @customer.destroy
            redirect_to customers_path, notice: "Cliente excluido com sucesso"
        else
            render :index
        end
    end

    private

    def set_customer
        @customer = Customer.find(params[:id])
    end

    def customers_params
        params.require(:customer).permit(:id, :name, :email, :smoker, :phone, :avatar)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<% if @customer.errors.any? %>
    <ul>
        <% @customer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
<% end %>

<h1>Editar Cliente</h1>

<%= form_for @customer do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :phone %>
    <%= f.text_field :phone %>

    <%= f.label :avatar %>
    <%= f.file_field :avatar %>

    <%= f.label :smoker %> <br />
    <% { "S": "Sim", "N": "Não" }.each do |key,value| %>
        <%= f.radio_button :smoker, key %> <%= value %> <br />
    <% end %>

    <%= f.submit "Editar Cliente" %>
<% end %>

app/views/customers/index.html.erb
<% if flash[:notice] %>
    <p><%= flash[:notice] %></p>
<% end %>

<h1>Lista de Clientes</h1>

<table>
    <thead>
        <tr>
            <td>Nome</td>
            <td></td>
            <td></td>
        </tr>
    </thead>

    <tbody>
        <% @customers.each do |customer| %>
        <tr>
            <td><%= customer.name %></td>
            <td> <%= link_to :Mostrar, customer_path(customer.id) %> </td>
            <td> <%= link_to :Editar, edit_customer_path(customer.id) %> </td>
            <td> <%= link_to :Excluir, customer, data: { "turbo-method": :delete, turbo_confirm: "Confirmar exclusão?" } %> </td>
        </tr>
        <% end %>
    </tbody>
</table>

<%= link_to "Novo Cliente", new_customer_path %>

app/views/customers/new.html.erb
<% if @customer.errors.any? %>
    <ul>
        <% @customer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
<% end %>

<h1>Novo Cliente</h1>

<%= form_for @customer do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :phone %>
    <%= f.text_field :phone %>

    <%= f.label :avatar %>
    <%= f.file_field :avatar %>

    <%= f.label :smoker %> <br />
    <% { "S": "Sim", "N": "Não" }.each do |key,value| %>
        <%= f.radio_button :smoker, key %> <%= value %> <br />
    <% end %>

    <%= f.submit "Criar Cliente" %>
<% end %>

app/views/customers/show.html.erb
<% if flash[:notice] %>
    <p><%= flash[:notice] %></p>
<% end %>

<h1>Mostrando Cliente</h1>

<p>
    <strong>Nome</strong>
    <%= @customer.name %>
</p>

<p>
    <strong>Email</strong>
    <%= @customer.email %>
</p>

<p>
    <strong>Telefone</strong>
    <%= @customer.phone %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudTdd</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Bem-Vindo!!</h1>

<ul>
    <li>
        <%= link_to "Cadastrar Cliente", customers_path %>
    </li>
</ul>